//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Latex4CorelDraw.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Latex4CorelDraw.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ScintillaNET&gt;
        ///	&lt;Language Name=&quot;default&quot;&gt;
        ///	&lt;Styles&gt;
        ///		&lt;Style Name=&quot;Default&quot; FontName=&quot;Consolas&quot; /&gt;
        ///	&lt;/Styles&gt;
        ///	&lt;/Language&gt;
        ///	&lt;Language Name=&quot;mytex&quot;&gt;
        ///		&lt;Indentation TabWidth=&quot;3&quot; UseSpaces=&quot;True&quot; SmartIndentType=&quot;cpp&quot;/&gt;
        ///		&lt;AutoComplete FillUpCharacters=&quot;&quot; SingleLineAccept=&quot;True&quot; IsCaseSensitive=&quot;False&quot;&gt;
        ///			&lt;List&gt;align begin end eqnarray equation hline hspace left matrix newline partial right table tabular vspace&lt;/List&gt;
        ///		&lt;/AutoComplete&gt;
        ///		&lt;Lexer LexerName=&quot;te [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \documentclass[12pt,a4paper]{article}
        ///\usepackage{amsmath} 
        ///\usepackage[utf8]{inputenc} 
        ///\usepackage{bbm} 
        ///\usepackage{ae,aecompl} 
        ///\usepackage{color}
        ///\usepackage[active,displaymath,textmath,tightpage]{preview}
        ///\newcommand{\changefont}[5]{\fontfamily{#1} \fontseries{#2} \fontshape{#3} \fontsize{#4}{#5}\selectfont}
        ///\setlength{\parindent}{0pt}
        ///\begin{document} 
        ///\thispagestyle{empty}
        ///
        ///${Content}
        ///
        ///\end{document}
        /// ähnelt.
        /// </summary>
        internal static string LatexTemplate {
            get {
                return ResourceManager.GetString("LatexTemplate", resourceCulture);
            }
        }
    }
}
